# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/phamanhtan/Developer/Equix/cboe-feed-handler-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/phamanhtan/Developer/Equix/cboe-feed-handler-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/phamanhtan/Developer/Equix/cboe-feed-handler-cpp/CMakeFiles /Users/phamanhtan/Developer/Equix/cboe-feed-handler-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/phamanhtan/Developer/Equix/cboe-feed-handler-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cboe_feed_handler

# Build rule for target.
cboe_feed_handler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cboe_feed_handler
.PHONY : cboe_feed_handler

# fast build rule for target.
cboe_feed_handler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/build
.PHONY : cboe_feed_handler/fast

src/MessageFactory.o: src/MessageFactory.cpp.o
.PHONY : src/MessageFactory.o

# target to build an object file
src/MessageFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/MessageFactory.cpp.o
.PHONY : src/MessageFactory.cpp.o

src/MessageFactory.i: src/MessageFactory.cpp.i
.PHONY : src/MessageFactory.i

# target to preprocess a source file
src/MessageFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/MessageFactory.cpp.i
.PHONY : src/MessageFactory.cpp.i

src/MessageFactory.s: src/MessageFactory.cpp.s
.PHONY : src/MessageFactory.s

# target to generate assembly for a file
src/MessageFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/MessageFactory.cpp.s
.PHONY : src/MessageFactory.cpp.s

src/UdpReceiver.o: src/UdpReceiver.cpp.o
.PHONY : src/UdpReceiver.o

# target to build an object file
src/UdpReceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/UdpReceiver.cpp.o
.PHONY : src/UdpReceiver.cpp.o

src/UdpReceiver.i: src/UdpReceiver.cpp.i
.PHONY : src/UdpReceiver.i

# target to preprocess a source file
src/UdpReceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/UdpReceiver.cpp.i
.PHONY : src/UdpReceiver.cpp.i

src/UdpReceiver.s: src/UdpReceiver.cpp.s
.PHONY : src/UdpReceiver.s

# target to generate assembly for a file
src/UdpReceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/UdpReceiver.cpp.s
.PHONY : src/UdpReceiver.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cboe_feed_handler.dir/build.make CMakeFiles/cboe_feed_handler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cboe_feed_handler"
	@echo "... src/MessageFactory.o"
	@echo "... src/MessageFactory.i"
	@echo "... src/MessageFactory.s"
	@echo "... src/UdpReceiver.o"
	@echo "... src/UdpReceiver.i"
	@echo "... src/UdpReceiver.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

